export const labels =
{
	GENERAL: {
		APPLICATION_NAME: "NexusVision - SASS platform providing AI based solutions",
		CREATOR: "Ayush Bhatt",
		AUTHOR: "Ayush Bhatt",
	},
	PAGE_TITLES: {
		SIGN_IN: "Sign In - NexusVision",
		SIGN_UP: "Sign Up - NexusVision",
		AR_SHOES: "AR/3D Shoes - NexusVision",
		AR_SHOES_DETAILS: "AR/3D Shoes Details - NexusVision",
		AR_VIEW: "AR Viewer - NexusVision",
		AI_CAMERA: "AI Camera - NexusVision",
		AI_CAMERA_SECURITY: "AI Camera Security - NexusVision",
	},
	PAGE_DESCRIPTIONS: {
		SIGN_IN: "Sign In | AI SASS | NexusVision",
		SIGN_UP: "Sign Up | AI SASS | NexusVision",
		AR_SHOES: "AR/3D Shoes | AI SASS | NexusVision",
		AR_SHOES_DETAILS: "AR/3D Shoes Details | AI SASS | NexusVision",
		AR_VIEW: "AR Viewer | AI SASS | NexusVision",
		AI_CAMERA: "AI Camera | AI SASS | NexusVision",
		AI_CAMERA_SECURITY: "AI Camera Security | AI SASS | NexusVision",
	},
	PAGE_KEYWORDS: {
		SIGN_IN: "SignIn, NexusVision, document, management, CMS, AI, powered, documents, bot, chatbot, sass",
		SIGN_UP: "SignUp, NexusVision, document, management, CMS, AI, powered, documents, bot, chatbot, sass",
		AR_SHOES: "AR, 3D, Shoes, NexusVision, document, management, CMS, AI, powered, documents, bot, chatbot, sass",
		AR_SHOES_DETAILS: "AR, 3D, Shoes, Details, NexusVision, document, management, CMS, AI, powered, documents, bot, chatbot, sass",
		AR_VIEW: "AR, Viewer, NexusVision, document, management, CMS, AI, powered, documents, bot, chatbot, sass",
		AI_CAMERA: "AI, Camera, NexusVision, document, management, CMS, AI, powered, documents, bot, chatbot, sass",
		AI_CAMERA_SECURITY: "AI, Camera, Security, NexusVision, document, management, CMS, AI, powered, documents, bot, chatbot, sass",
	},
	ERROR_BOUNDARY: {
		HEADING: "Something went wrong",
		BTN: "Try Again",
		DESCRIPTION: "Unexpected error occurred. Please click on the button below to try again.",
	},
	AUTH: {
		HEADING_1: "Step into",
		HEADING_2: "new era of 3D & AR",
		HEADING_3: "With Artificial Intelligence",
	},
	AR_SHOES_HOME: {
		FAQS: "FAQs",
		AR: "AUGMENTED REALITY",
		VIEWER_3D: "3D VIEWER",
		HEADING_1: "BOARING",
		HEADING_2: "SHOES ?",
		HEADING_3: "Let Us",
		HEADING_4: "HELP",
		HEADING_5: "you fix it...",
		EXPLORE_BTN: "EXPLORE OUR STORE",
		VIEW_BTN: "VIEW IN 3D/AR",
	},
	AR_SHOES_DETAILS: {
		VIEWER_3D_BTN: "3D Viewer",
		VIEWER_AR_BTN: "View in AR",
	},
	AI_CAMERA: {
		HEADING_1: "AI-Powered",
		HEADING_2: "Security",
		HEADING_3: "for Unparalleled",
		HEADING_4: "Belongings Protection",
		DESCRIPTION: "Security builds for the future. Meet the fastest most secure, and complaint platform",
		GET_STARTED: "Get Started",
		REALITY_CHECK: "AI Reality Sync",
	},
	AI_SECURITY: {
		HEADING: "AI Powered Object Detection",
		START_BTN: "Start",
		STOP_BTN: "Stop",
		SET_PASSWORD: "Set Password",
		SET_PASS_PLACEHOLDER: "Set Password...",
		CANCEL_BTN: "Cancel",
		STOP_CAMERA_BTN: "Stop Camera",
		ENTER_PASS: "Enter Password",
		ENTER_PASS_PLACEHOLDER: "Enter your password...",
		INVALID_PASS: "Invalid Password",
	},
	OTHERS: {
		FOOTER: "Copyright © NexusVision (Hack-A-League IQ Solutions Pvt. Ltd) • All Rights Reserved",
		CLIPBOARD_FAILED: "Failed to copy to clipboard",
		CLIPBOARD_NOT_SUPPORTED: "Copy to clipboard is not supported in your browser",
	}
} as const;